version: '3'

services:
  buildserver:
    image: bmordan/build-server:latest
    ports:
      - "3030:3030"
    environment:
      NODE_ENV: production 
    env_file:
      - mailchimp.env
    restart: always
  nginx:
    image: nginx
    depends_on:
      - buildserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /docker-volumes/etc/letsencrypt/live/christianmuslimforum.net/fullchain.pem:/etc/letsencrypt/live/christianmuslimforum.net/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/christianmuslimforum.net/privkey.pem:/etc/letsencrypt/live/christianmuslimforum.net/privkey.pem
    restart: always