version: '3'

services:
  buildserver:
    image: bmordan/build-server
    ports:
      - "3030:3030"
    environment:
      BUILD_SERVER_PORT: 3030
      NODE_ENV: production
    restart: always
  nginx:
      image: nginx
      depends_on:
          - buildserver
      ports:
          - "80:80"
      volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
      restart: always